const allTickerWatchers = [
    "ticker-watchers-under1-shouldWatchout-minorJump-morning-5000",
    "ticker-watchers-under1-shouldWatchout-minorJump-morning-failedHistorical-5000",
    "ticker-watchers-under1-shouldWatchout-minorJump-later-5000",
    "ticker-watchers-under1-shouldWatchout-minorJump-later-failedHistorical-5000",
    "ticker-watchers-under1-shouldWatchout-minorJump-muchlater-5000",
    "ticker-watchers-under1-shouldWatchout-minorJump-muchlater-failedHistorical-5000",
    "ticker-watchers-under1-shouldWatchout-majorJump-morning-5000",
    "ticker-watchers-under1-shouldWatchout-majorJump-morning-failedHistorical-5000",
    "ticker-watchers-under1-shouldWatchout-majorJump-later-5000",
    "ticker-watchers-under1-shouldWatchout-majorJump-later-failedHistorical-5000",
    "ticker-watchers-under1-shouldWatchout-majorJump-muchlater-5000",
    "ticker-watchers-under1-shouldWatchout-majorJump-muchlater-failedHistorical-5000",
    "ticker-watchers-under1-shouldWatchout-morning-5000",
    "ticker-watchers-under1-shouldWatchout-morning-failedHistorical-5000",
    "ticker-watchers-under1-shouldWatchout-later-5000",
    "ticker-watchers-under1-shouldWatchout-later-failedHistorical-5000",
    "ticker-watchers-under1-shouldWatchout-muchlater-5000",
    "ticker-watchers-under1-shouldWatchout-muchlater-failedHistorical-5000",
    "ticker-watchers-under1-notWatchout-minorJump-morning-5000",
    "ticker-watchers-under1-notWatchout-minorJump-morning-failedHistorical-5000",
    "ticker-watchers-under1-notWatchout-minorJump-later-5000",
    "ticker-watchers-under1-notWatchout-minorJump-later-failedHistorical-5000",
    "ticker-watchers-under1-notWatchout-minorJump-muchlater-5000",
    "ticker-watchers-under1-notWatchout-minorJump-muchlater-failedHistorical-5000",
    "ticker-watchers-under1-notWatchout-majorJump-morning-5000",
    "ticker-watchers-under1-notWatchout-majorJump-morning-failedHistorical-5000",
    "ticker-watchers-under1-notWatchout-majorJump-later-5000",
    "ticker-watchers-under1-notWatchout-majorJump-later-failedHistorical-5000",
    "ticker-watchers-under1-notWatchout-majorJump-muchlater-5000",
    "ticker-watchers-under1-notWatchout-majorJump-muchlater-failedHistorical-5000",
    "ticker-watchers-under1-notWatchout-morning-5000",
    "ticker-watchers-under1-notWatchout-morning-failedHistorical-5000",
    "ticker-watchers-under1-notWatchout-later-5000",
    "ticker-watchers-under1-notWatchout-later-failedHistorical-5000",
    "ticker-watchers-under1-notWatchout-muchlater-5000",
    "ticker-watchers-under1-notWatchout-muchlater-failedHistorical-5000",
    "ticker-watchers-under5-shouldWatchout-minorJump-morning-5000",
    "ticker-watchers-under5-shouldWatchout-minorJump-morning-failedHistorical-5000",
    "ticker-watchers-under5-shouldWatchout-minorJump-later-5000",
    "ticker-watchers-under5-shouldWatchout-minorJump-later-failedHistorical-5000",
    "ticker-watchers-under5-shouldWatchout-minorJump-muchlater-5000",
    "ticker-watchers-under5-shouldWatchout-minorJump-muchlater-failedHistorical-5000",
    "ticker-watchers-under5-shouldWatchout-majorJump-morning-5000",
    "ticker-watchers-under5-shouldWatchout-majorJump-morning-failedHistorical-5000",
    "ticker-watchers-under5-shouldWatchout-majorJump-later-5000",
    "ticker-watchers-under5-shouldWatchout-majorJump-later-failedHistorical-5000",
    "ticker-watchers-under5-shouldWatchout-majorJump-muchlater-5000",
    "ticker-watchers-under5-shouldWatchout-majorJump-muchlater-failedHistorical-5000",
    "ticker-watchers-under5-shouldWatchout-morning-5000",
    "ticker-watchers-under5-shouldWatchout-morning-failedHistorical-5000",
    "ticker-watchers-under5-shouldWatchout-later-5000",
    "ticker-watchers-under5-shouldWatchout-later-failedHistorical-5000",
    "ticker-watchers-under5-shouldWatchout-muchlater-5000",
    "ticker-watchers-under5-shouldWatchout-muchlater-failedHistorical-5000",
    "ticker-watchers-under5-notWatchout-minorJump-morning-5000",
    "ticker-watchers-under5-notWatchout-minorJump-morning-failedHistorical-5000",
    "ticker-watchers-under5-notWatchout-minorJump-later-5000",
    "ticker-watchers-under5-notWatchout-minorJump-later-failedHistorical-5000",
    "ticker-watchers-under5-notWatchout-minorJump-muchlater-5000",
    "ticker-watchers-under5-notWatchout-minorJump-muchlater-failedHistorical-5000",
    "ticker-watchers-under5-notWatchout-majorJump-morning-5000",
    "ticker-watchers-under5-notWatchout-majorJump-morning-failedHistorical-5000",
    "ticker-watchers-under5-notWatchout-majorJump-later-5000",
    "ticker-watchers-under5-notWatchout-majorJump-later-failedHistorical-5000",
    "ticker-watchers-under5-notWatchout-majorJump-muchlater-5000",
    "ticker-watchers-under5-notWatchout-majorJump-muchlater-failedHistorical-5000",
    "ticker-watchers-under5-notWatchout-morning-5000",
    "ticker-watchers-under5-notWatchout-morning-failedHistorical-5000",
    "ticker-watchers-under5-notWatchout-later-5000",
    "ticker-watchers-under5-notWatchout-later-failedHistorical-5000",
    "ticker-watchers-under5-notWatchout-muchlater-5000",
    "ticker-watchers-under5-notWatchout-muchlater-failedHistorical-5000",
    "ticker-watchers-under10-shouldWatchout-minorJump-morning-5000",
    "ticker-watchers-under10-shouldWatchout-minorJump-morning-failedHistorical-5000",
    "ticker-watchers-under10-shouldWatchout-minorJump-later-5000",
    "ticker-watchers-under10-shouldWatchout-minorJump-later-failedHistorical-5000",
    "ticker-watchers-under10-shouldWatchout-minorJump-muchlater-5000",
    "ticker-watchers-under10-shouldWatchout-minorJump-muchlater-failedHistorical-5000",
    "ticker-watchers-under10-shouldWatchout-majorJump-morning-5000",
    "ticker-watchers-under10-shouldWatchout-majorJump-morning-failedHistorical-5000",
    "ticker-watchers-under10-shouldWatchout-majorJump-later-5000",
    "ticker-watchers-under10-shouldWatchout-majorJump-later-failedHistorical-5000",
    "ticker-watchers-under10-shouldWatchout-majorJump-muchlater-5000",
    "ticker-watchers-under10-shouldWatchout-majorJump-muchlater-failedHistorical-5000",
    "ticker-watchers-under10-shouldWatchout-morning-5000",
    "ticker-watchers-under10-shouldWatchout-morning-failedHistorical-5000",
    "ticker-watchers-under10-shouldWatchout-later-5000",
    "ticker-watchers-under10-shouldWatchout-later-failedHistorical-5000",
    "ticker-watchers-under10-shouldWatchout-muchlater-5000",
    "ticker-watchers-under10-shouldWatchout-muchlater-failedHistorical-5000",
    "ticker-watchers-under10-notWatchout-minorJump-morning-5000",
    "ticker-watchers-under10-notWatchout-minorJump-morning-failedHistorical-5000",
    "ticker-watchers-under10-notWatchout-minorJump-later-5000",
    "ticker-watchers-under10-notWatchout-minorJump-later-failedHistorical-5000",
    "ticker-watchers-under10-notWatchout-minorJump-muchlater-5000",
    "ticker-watchers-under10-notWatchout-minorJump-muchlater-failedHistorical-5000",
    "ticker-watchers-under10-notWatchout-majorJump-morning-5000",
    "ticker-watchers-under10-notWatchout-majorJump-morning-failedHistorical-5000",
    "ticker-watchers-under10-notWatchout-majorJump-later-5000",
    "ticker-watchers-under10-notWatchout-majorJump-later-failedHistorical-5000",
    "ticker-watchers-under10-notWatchout-majorJump-muchlater-5000",
    "ticker-watchers-under10-notWatchout-majorJump-muchlater-failedHistorical-5000",
    "ticker-watchers-under10-notWatchout-morning-5000",
    "ticker-watchers-under10-notWatchout-morning-failedHistorical-5000",
    "ticker-watchers-under10-notWatchout-later-5000",
    "ticker-watchers-under10-notWatchout-later-failedHistorical-5000",
    "ticker-watchers-under10-notWatchout-muchlater-5000",
    "ticker-watchers-under10-notWatchout-muchlater-failedHistorical-5000",
    "ticker-watchers-under15-shouldWatchout-minorJump-morning-5000",
    "ticker-watchers-under15-shouldWatchout-minorJump-morning-failedHistorical-5000",
    "ticker-watchers-under15-shouldWatchout-minorJump-later-5000",
    "ticker-watchers-under15-shouldWatchout-minorJump-later-failedHistorical-5000",
    "ticker-watchers-under15-shouldWatchout-minorJump-muchlater-5000",
    "ticker-watchers-under15-shouldWatchout-minorJump-muchlater-failedHistorical-5000",
    "ticker-watchers-under15-shouldWatchout-majorJump-morning-5000",
    "ticker-watchers-under15-shouldWatchout-majorJump-morning-failedHistorical-5000",
    "ticker-watchers-under15-shouldWatchout-majorJump-later-5000",
    "ticker-watchers-under15-shouldWatchout-majorJump-later-failedHistorical-5000",
    "ticker-watchers-under15-shouldWatchout-majorJump-muchlater-5000",
    "ticker-watchers-under15-shouldWatchout-majorJump-muchlater-failedHistorical-5000",
    "ticker-watchers-under15-shouldWatchout-morning-5000",
    "ticker-watchers-under15-shouldWatchout-morning-failedHistorical-5000",
    "ticker-watchers-under15-shouldWatchout-later-5000",
    "ticker-watchers-under15-shouldWatchout-later-failedHistorical-5000",
    "ticker-watchers-under15-shouldWatchout-muchlater-5000",
    "ticker-watchers-under15-shouldWatchout-muchlater-failedHistorical-5000",
    "ticker-watchers-under15-notWatchout-minorJump-morning-5000",
    "ticker-watchers-under15-notWatchout-minorJump-morning-failedHistorical-5000",
    "ticker-watchers-under15-notWatchout-minorJump-later-5000",
    "ticker-watchers-under15-notWatchout-minorJump-later-failedHistorical-5000",
    "ticker-watchers-under15-notWatchout-minorJump-muchlater-5000",
    "ticker-watchers-under15-notWatchout-minorJump-muchlater-failedHistorical-5000",
    "ticker-watchers-under15-notWatchout-majorJump-morning-5000",
    "ticker-watchers-under15-notWatchout-majorJump-morning-failedHistorical-5000",
    "ticker-watchers-under15-notWatchout-majorJump-later-5000",
    "ticker-watchers-under15-notWatchout-majorJump-later-failedHistorical-5000",
    "ticker-watchers-under15-notWatchout-majorJump-muchlater-5000",
    "ticker-watchers-under15-notWatchout-majorJump-muchlater-failedHistorical-5000",
    "ticker-watchers-under15-notWatchout-morning-5000",
    "ticker-watchers-under15-notWatchout-morning-failedHistorical-5000",
    "ticker-watchers-under15-notWatchout-later-5000",
    "ticker-watchers-under15-notWatchout-later-failedHistorical-5000",
    "ticker-watchers-under15-notWatchout-muchlater-5000",
    "ticker-watchers-under15-notWatchout-muchlater-failedHistorical-5000",
    "ticker-watchers-under20-shouldWatchout-minorJump-morning-5000",
    "ticker-watchers-under20-shouldWatchout-minorJump-morning-failedHistorical-5000",
    "ticker-watchers-under20-shouldWatchout-minorJump-later-5000",
    "ticker-watchers-under20-shouldWatchout-minorJump-later-failedHistorical-5000",
    "ticker-watchers-under20-shouldWatchout-minorJump-muchlater-5000",
    "ticker-watchers-under20-shouldWatchout-minorJump-muchlater-failedHistorical-5000",
    "ticker-watchers-under20-shouldWatchout-majorJump-morning-5000",
    "ticker-watchers-under20-shouldWatchout-majorJump-morning-failedHistorical-5000",
    "ticker-watchers-under20-shouldWatchout-majorJump-later-5000",
    "ticker-watchers-under20-shouldWatchout-majorJump-later-failedHistorical-5000",
    "ticker-watchers-under20-shouldWatchout-majorJump-muchlater-5000",
    "ticker-watchers-under20-shouldWatchout-majorJump-muchlater-failedHistorical-5000",
    "ticker-watchers-under20-shouldWatchout-morning-5000",
    "ticker-watchers-under20-shouldWatchout-morning-failedHistorical-5000",
    "ticker-watchers-under20-shouldWatchout-later-5000",
    "ticker-watchers-under20-shouldWatchout-later-failedHistorical-5000",
    "ticker-watchers-under20-shouldWatchout-muchlater-5000",
    "ticker-watchers-under20-shouldWatchout-muchlater-failedHistorical-5000",
    "ticker-watchers-under20-notWatchout-minorJump-morning-5000",
    "ticker-watchers-under20-notWatchout-minorJump-morning-failedHistorical-5000",
    "ticker-watchers-under20-notWatchout-minorJump-later-5000",
    "ticker-watchers-under20-notWatchout-minorJump-later-failedHistorical-5000",
    "ticker-watchers-under20-notWatchout-minorJump-muchlater-5000",
    "ticker-watchers-under20-notWatchout-minorJump-muchlater-failedHistorical-5000",
    "ticker-watchers-under20-notWatchout-majorJump-morning-5000",
    "ticker-watchers-under20-notWatchout-majorJump-morning-failedHistorical-5000",
    "ticker-watchers-under20-notWatchout-majorJump-later-5000",
    "ticker-watchers-under20-notWatchout-majorJump-later-failedHistorical-5000",
    "ticker-watchers-under20-notWatchout-majorJump-muchlater-5000",
    "ticker-watchers-under20-notWatchout-majorJump-muchlater-failedHistorical-5000",
    "ticker-watchers-under20-notWatchout-morning-5000",
    "ticker-watchers-under20-notWatchout-morning-failedHistorical-5000",
    "ticker-watchers-under20-notWatchout-later-5000",
    "ticker-watchers-under20-notWatchout-later-failedHistorical-5000",
    "ticker-watchers-under20-notWatchout-muchlater-5000",
    "ticker-watchers-under20-notWatchout-muchlater-failedHistorical"
];



const TWshouldWatchout = allTickerWatchers.filter(s => s.includes('shouldWatchout'));
const TWnotWatchout = allTickerWatchers.filter(s => s.includes('notWatchout'));

const TWminorJumps = allTickerWatchers.filter(s => s.includes('minorJump') && !s.includes('failedHistorical'));
const TWmajorJumps = allTickerWatchers.filter(s => s.includes('majorJump') && !s.includes('failedHistorical'));
const TWfailedHistorical = allTickerWatchers.filter(s => s.includes('failedHistorical'));
const TWnotWatchoutNoFailedHistOrMinorJumps = allTickerWatchers.filter(
    s => s.includes('notWatchout') 
    && !s.includes('failedHistorical')
    && !s.includes('minorJump')
);


const TWmorning = allTickerWatchers.filter(s => s.includes('morning'));
const TWlater = allTickerWatchers.filter(s => s.includes('later') && !s.includes('muchlater'));
const TWmuchLater = allTickerWatchers.filter(s => s.includes('muchlater'));


let myTickerWatchers = [
    ...TWmajorJumps,
    ...TWnotWatchoutNoFailedHistOrMinorJumps,
    ...TWnotWatchoutNoFailedHistOrMinorJumps
].filter(s => s.includes('under1-') || s.includes('under5'));

const myLaters = [
    ...new Set(
        myTickerWatchers
            .filter(s => s.includes('later'))
            .filter(s => s.includes('under1-') || s.includes('under5'))
    )
];
    
myTickerWatchers = myTickerWatchers
    .concat(myLaters)
    .filter(s => !(s.includes('shouldWatchout') && s.includes('morning')));

module.exports = {
    allTickerWatchers,
    myTickerWatchers,
    TWnotWatchoutNoFailedHistOrMinorJumps,
    TWnotWatchout,
    TWshouldWatchout,
    TWfailedHistorical,
    TWmajorJumps,
    TWminorJumps,
    TWmorning,
    TWlater,
    TWmuchLater,
    myLaters
};
